name: Bloomee
description: An Open source Free Music Player.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.11.6+0

environment:
  sdk: '>=3.0.6 <4.0.0'

# isar version for community fork of isar (temporary)
isar_version: &isar_version 3.1.8

dependencies:
  flutter:
    sdk: flutter

  device_info_plus: ^10.1.0
  equatable: ^2.0.7
  icons_plus: ^5.0.0
  # due to metadata god
  cached_network_image: ^3.3.1
  flutter_bloc: ^9.0.0
  dart_des: ^1.0.2
  http: ^1.2.2
  convert: ^3.1.1
  html: ^0.15.4
  logging: ^1.2.0
  google_nav_bar: ^5.0.6
  carousel_slider: ^5.0.0
  palette_generator: ^0.3.3+2
  audio_video_progress_bar: ^1.0.1
  just_audio: ^0.9.42
  audio_service: ^0.18.16
  audio_session: ^0.1.16
  rxdart: ^0.27.7
  go_router: ^14.8.1
  easy_debounce: ^2.0.3

  isar: 
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: *isar_version
    hosted: https://pub.isar-community.dev/

  path_provider: ^2.1.0
  modal_bottom_sheet: ^3.0.0
  youtube_explode_dart:
    # path: ../youtube_explode_dart
    git:
      url: https://github.com/HemantKArya/youtube_explode_dart.git
      ref: master
  html_unescape: ^2.0.0
  marquee: ^2.2.3
  string_similarity: ^2.0.0
  package_info_plus: ^4.2.0
  url_launcher: ^6.3.0
  badges: ^3.1.2
  flutter_displaymode: ^0.6.0
  connectivity_plus: ^5.0.2
  share_plus: ^7.2.2
  file_picker: ^8.0.0+1
  fuzzywuzzy: ^1.1.6
  numberpicker: ^2.1.2
  flutter_downloader: ^1.11.6
  metadata_god: ^0.5.2+1
  permission_handler: ^11.3.1
  receive_sharing_intent: ^1.8.0
  sliding_up_panel: ^2.0.0+1
  responsive_framework: ^1.4.0
  scrollable_positioned_list: ^0.3.8
  crypto: ^3.0.5
  dart_discord_rpc: ^0.0.2

  # linux plugins
  just_audio_media_kit: ^2.0.6
  media_kit_libs_linux: any
  media_kit_libs_windows_audio: any
  audio_service_mpris: ^0.2.0
  # mime: ^1.0.5

dependency_overrides:
  ffi: ^1.1.2  # Override to make dart_discord_rpc work


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

  isar_generator: 
    version: *isar_version
    hosted: https://pub.isar-community.dev/
    
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  # icons_launcher: ^2.1.7


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# dart run icons_launcher:create
# icons_launcher:
#   image_path: "assets/icons/new_bloomee_logo_zoomedout.png"
#   platforms:
#     android:
#       enable: true
#       adaptive_icon_background: "assets/icons/bloomee_new_logo_gradient_bg.png"
#       adaptive_icon_foreground: "assets/icons/new_bloomee_logo_zoomedout.png"
#       adaptive_monochrome_image: "assets/icons/new_bloomee_logo_mono.png"
#     ios:
#       enable: true
#     windows:
#       enable: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "assets/icons/bloomee_new_logo_gradient_bg.png"
  adaptive_icon_foreground: "assets/icons/new_bloomee_logo_zoomedout.png"
  image_path: "assets/icons/bloomee_new_logo_transparent_c.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  macos:
    generate: true
    image_path: "assets/icons/bloomee_new_logo_c.png"
  windows:
    generate: true
    image_path: "assets/icons/bloomee_new_logo_transparent_c.png"
    

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/bloomee_new_logo_c.png
    - assets/icons/lazy_loading.png
    
  fonts:
    - family: Unageo
      fonts:
        - asset: assets/fonts/Unageo/Unageo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Unageo/Unageo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Unageo/Unageo-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Unageo/Unageo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Unageo/Unageo-Extrabold.ttf
          weight: 800
        - asset: assets/fonts/Unageo/Unageo-Black.ttf
          weight: 900
    
        
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy/Gilroy-Medium.ttf
          weight: 700
        - asset: assets/fonts/Gilroy/Gilroy-Bold.ttf
          weight: 900
    - family: CodePro
      fonts:
        - asset: assets/fonts/CodePro/Code Pro LC.otf
          weight: 400
        - asset: assets/fonts/CodePro/Code Pro Bold LC.otf
          weight: 700

    - family: ReThink-Sans
      fonts:
        - asset: assets/fonts/ReThinkSans/RethinkSans-Regular.otf
          weight: 400
        - asset: assets/fonts/ReThinkSans/RethinkSans-Medium.otf
          weight: 500
        - asset: assets/fonts/ReThinkSans/RethinkSans-SemiBold.otf
          weight: 600
        - asset: assets/fonts/ReThinkSans/RethinkSans-Bold.otf
          weight: 700
        - asset: assets/fonts/ReThinkSans/RethinkSans-ExtraBold.otf
          weight: 800
          
    - family: NotoSans
      fonts:
        - asset: assets/fonts/Noto/NotoSans-VariableFont_wdth,wght.ttf


    - family: Fjalla
      fonts:
        - asset: assets/fonts/Fjalla/FjallaOne-Regular.ttf
    - family: FontAwesome-Brands
      fonts:
        - asset: assets/fonts/fontawesome-free-6.4.0-desktop/otfs/Font Awesome 6 Brands-Regular-400.otf
    - family: FontAwesome-Regular
      fonts:
        - asset: assets/fonts/fontawesome-free-6.4.0-desktop/otfs/Font Awesome 6 Free-Regular-400.otf
    - family: FontAwesome-Solids
      fonts:
        - asset: assets/fonts/fontawesome-free-6.4.0-desktop/otfs/Font Awesome 6 Free-Solid-900.otf

